import {
  Award,
  BadgeCheck,
  Briefcase,
  Building2,
  Camera,
  Check,
  ClipboardList,
  Clock3,
  Compass,
  Cpu,
  Eye,
  Flag,
  GraduationCap,
  HandHeart,
  HardHat,
  Info,
  Lightbulb,
  Lock,
  Mail,
  Map,
  MessageSquare,
  Monitor,
  Phone,
  Route,
  Scale,
  Search,
  Shield,
  Sparkles,
  Target,
  User,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from '@/data/content';

/** Maps the content layer's icon names to components, keeping data free of JSX. */
export const ICONS: Record<IconName, LucideIcon> = {
  compass: Compass,
  cpu: Cpu,
  route: Route,
  building: Building2,
  scale: Scale,
  shield: Shield,
  info: Info,
  mail: Mail,
  flag: Flag,
  clock: Clock3,
  badge: BadgeCheck,
  users: Users,
  wrench: Wrench,
  clipboard: ClipboardList,
  zap: Zap,
  hardhat: HardHat,
  eye: Eye,
  phone: Phone,
  map: Map,
  target: Target,
  award: Award,
  sparkle: Sparkles,
  handshake: HandHeart,
  lightbulb: Lightbulb,
  lock: Lock,
  camera: Camera,
  monitor: Monitor,
  briefcase: Briefcase,
  graduation: GraduationCap,
  search: Search,
  message: MessageSquare,
  check: Check,
  user: User,
};
