import {
  BadgeCheck,
  Building2,
  ClipboardList,
  Clock3,
  Compass,
  Cpu,
  Eye,
  Flag,
  HardHat,
  Info,
  Mail,
  Map,
  Phone,
  Route,
  Scale,
  Shield,
  Users,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import type { IconName } from '@/data/content';

/** Maps the content layer's icon names to components, keeping data free of JSX. */
export const ICONS: Record<IconName, LucideIcon> = {
  compass: Compass,
  cpu: Cpu,
  route: Route,
  building: Building2,
  scale: Scale,
  shield: Shield,
  info: Info,
  mail: Mail,
  flag: Flag,
  clock: Clock3,
  badge: BadgeCheck,
  users: Users,
  wrench: Wrench,
  clipboard: ClipboardList,
  zap: Zap,
  hardhat: HardHat,
  eye: Eye,
  phone: Phone,
  map: Map,
};
